export default [
  {
    id: 10356,
    postedOn: "2024-10-2",
    title: "IOS Developer",
    company: "Apple",
    area:"Noida",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["C,java,Kotlin,DSA"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 2,
    postedOn: "2024-9-30",
    title: "Software Developer",
    company: "Amazon",
    area:"Gurugram",
    type: "Part Time",
    experience: "Fresher",
    location: "In-office",
    skills: ["Core java,Ad.java,DSA,OOPS,logical Programming"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 3,
    postedOn: "2024-9-27",
    title: "Frontend Developer",
    company: "Google",
    area:"Delhi",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["Html,CSS,js,Reactjs,Tailwind CSS"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 47852,
    postedOn: "2024-10-9",
    title: "Data Anaylst",
    company: "Adobe",
    area:"Noida",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SQL,NOSQL,Python,Ruby"],
    job_link: "https://www.apple.com/careers/in/",
  }
];